# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ProdOps Guides
email: leefaus@github.com
description: > # ProdOps: From Product to Production.  The future of DevOps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://prodops.guide" # the base hostname & protocol for your site
twitter_username: leefaus
github_username:  leefaus

# Build settings
markdown: kramdown
gems: [bootstrap, autoprefixer-rails, jekyll-assets, jekyll-sitemap]
sass:
    sass_dir: _sass

assets:
  compress:
      css: true
      js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

baseurl: /

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

ga_analytics: # Add Google Analytics tracking code

name: ProdOps Guides

permalink: pretty
